docs/about.md
docs/programming.md
docs/programming/reference.md
docs/programming/reference/runes.md
docs/programming/reference/runes/bc.md
docs/programming/reference/runes/br.md
docs/programming/reference/runes/cl.md
docs/programming/reference/runes/cn.md
docs/programming/reference/runes/dt.md
docs/programming/reference/runes/hx.md
docs/programming/reference/runes/kt.md
docs/programming/reference/runes/sg.md
docs/programming/reference/runes/sm.md
docs/programming/reference/runes/ts.md
docs/programming/reference/runes/wt.md
docs/programming/reference/runes/zp.md
docs/using.md
docs/using/setup.md
docs/using/web.md

relies on tree@0cb119c, fixes #5

Change usage of dataPath to src

---

docs/nock/implementations/groovy.md
docs/nock/implementations/hoon.md

I've put together a simple interpreter for the sake of learning a bit of Nock and to understand Hoon eventually. I've added a new implementation page. The actual code has some tests in it, feel free to review it. Suggestions are more than welcome.
One question: can we link/import the actual code file from the origin repo directly? W/o copy-pasta? (I'm not sure if it's doable.)
Edit: I've noticed the `next: true` thingy in the doc files (and that it was missing from from `hoon.md`). Not sure what that is. Hope I've got it right.

Nock interpreter in Groovy

---

docs/nock/implementations/hoon.md
docs/nock/implementations/javascript.md

It had to be done ...
I've tested this pretty thoroughly, and I'm reasonably sure it's correct ;)
Let me know if you'd prefer it stripped down; it's obviously pretty long, and about half is the comments, module wrapper, exports, etc.

adds js nock implementation

---

docs/nock/implementations/hoon.md
docs/nock/implementations/swift.md

A Nock interpreter and compiler in Swift.

Nock implementation in Swift.

---

docs/hoon/twig/buc-mold.md
docs/hoon/twig/cen-call/tis-make.md
docs/hoon/twig/tis-flow/fas-var.md
docs/hoon/twig/tis-flow/sem-rev.md
docs/hoon/twig/wut-test/col-if.md

also fixes some expansion paren nesting

fixes cases where forms were called as in :wad(gate)

---

docs/arvo/subject.md

Update command line argument in cheatsheet

---

docs/using/messaging.md

This seems to come up a fair amount in `:talk`...

adds ;leave to :talk page

---

docs/arvo/network.md

Hopefully this is correct. It matches what I've run against current urbit with success. #45

Fix failing network examples

---

docs/about/glossary.md
docs/using/setup.md

I've covered Nock, I *think* I've covered Hoon. Arvo and general urbit-y concepts are yet to be defined.
I've added *TODO* wherever I was stuck, guessing, or more-than-usually confused.
I took a stab at some formatting, but there's lots of different ways this could be structured. Likewise, I moved things around until it felt like their order made sense, but I'm not at all sure that it's right ...
Finally, I'm not sure this is written in the right voice. It needs to strike the right balance tonally, since I image it'll be consulted quite a bit.
This glossary is provided AS IS, without warranty or encumbrance on it's author ;)
re #33, #26

adds initial glossary

---

docs/hoon/twig/wut-test/zap-not.md

Also adds a *regular*-form example

corrects ?! irregular form in the twigs reference

---

docs/arvo/basic.md

subdirectory off by one error

---

docs/hoon/syntax.md

Nothing too important, just trying to fix a few things that I mentally tripped over while reading the docs.

Fix a couple typos.

---

docs/about/glossary.md

It should be clear from the get go what a person is actually given.
A person unfamiliar with crypto's limitations, might make bad assumptions.
___
There should probably be more said and more clarified elsewhere, but, for the mean time, this edit raises enough questions for the reader to make a prudent individual weary of making any assumptions. 
___
I realize the concept of a "will" may still be young, and a bit unclear with how it should be defined. 
But, it should still be brought up early, as from what I can tell it's quite important.

Key association clarification.

---

docs/arvo/http.md

Bring content of arvo/http in line with example code

---

docs/hoon/twig/atom/knit.md
docs/hoon/twig/bar-core/dot-trap.md

A few typos I found when reading through docs.

Tiny typo fixes

---

docs/using/admin.md

Not sure if this is desired, or if it goes outside of the scope of the docs, but this would prevent people from running into urbit/urbit#748.

Instructions for logging Urbit's output

---

docs/about/objections.md

Added a tautological reason to run Urbit -- could be replaced by a non-tautological reason

Fix unfinished sentence

---

docs/using/messaging.md

What it says on the box. Quiet flag from urbit/arvo#300.
I'll update this to include the flag in urbit/arvo#308 if it gets accepted.

Mention the quiet flag in talk documentation.

---

docs/arvo/basic.md
docs/using/shell.md

whitespace usage really threw me, it's not mentioned until later in the hoon documentation

line numbers are off, whitespace

---

docs/byte/0.md
docs/byte/1.md
docs/byte/2.md

Boot comet not fake ~zod in Urbytes.

---

docs.md

Touches up our community/social-media links and our links to our source
code. Fixes some known hyperlinking problems (closed issues knowing I was going to PR this).
Looks like this:
I could add some more text to fill up the white space. Also just open to any changes / dislikes in general.

Pretty side panel

---

docs/arvo/basic.md
docs/arvo/subject.md

Keeps thing in style. Just a few fixes.

Fixes some Hoon empty lines in docs/arvo.

---

docs/arvo/generators.md
docs/arvo/http.md
docs/arvo/security-driver.md
docs/arvo/web-apps.md

Keeps in style with rest of docs.

Fix inconsistent capitalization.

---

docs/community-docs.md

Think I just copied and pasted wrong.

Fix ~hidduc-posmeg community docs link

---

docs/arvo/state.md

Something I caught a while ago I guess.

Fix syntax

---

docs/arvo/basic.md

pel to pal 
per to par 
sig added

copied glyph pronunciation table from hoon/syntax.md

---

docs/using/shell.md

I hit this one myself so thought I'd contribute back.
I couldn't figure out exactly where it made sense to include, so I did this by adding a Troubleshooting section. Other suggestions are welcome.

Fixes #132: Tells what to do when you encounter a %dy-edit-busy in the dojo

---

docs/using/messaging.md

Question came up in urbit-meta today. Seemed like a good addition.
This is ~hosneb-rosler / ~darlur, ftr. ;)

Add information about ;what to messaging docs

---

docs/using/install.md

Updated everything except FreeBSD since that URL 404s.

Update download links to urbit 0.4.5

---

docs/arvo/internals/gall.md

misspelling

---

docs/byte/1.md

Changed ".n" and ".y" to "%.n" and "%.y"

revise Loobean values

---

docs/byte/2.md

Following up on discussion at issue #160:
https://github.com/urbit/docs/issues/160

Expanding explanation of tree addressing

---

docs/hoon/demo.md

I tried to make the explanation of the FizzBuzz demo more approachable for those who lack functional programming experience (or any programming experience, for that matter).  Feedback is welcome, but FWIW I remember finding a few lines really puzzling when I first worked through this as a beginner a few months ago.  I think these changes sand away some of the sharper edges.

More hand-holding in FizzBuzz demo

---

docs/hoon/twig/sem-make/sig-dip.md

hopefully this is clarifying ...

expand/explain :dip

---

docs/hoon/basic.md

The revisions to the first half were somewhat more heavy-handed and may be controversial.  Happy to discuss.

Updating the Basic Types Doc

---

docs/hoon/basic.md

No set theory jokes this time.

More revisions to the Basic Type doc

---

docs/using/install.md

review: @keatondunsford 
cc: @ohAitch

Call out pkg-config as a dependency.

---

docs/hoon/examples.md

`+-  tap` is no longer a gate, old code caused sieve.hoon not to compile.

corrected sieve example

---

docs/hoon/rune/cen/sig.md

Update doc to correct signature of %~ %cnsg

---

docs/hoon/rune/tis/com.md

Basic page addition for a rune that isn't yet documented

Add rune documentation for `=,`

---

docs/using/install.md

I'm making this PR to suggest the fix that helped me with my problem https://github.com/urbit/urbit/issues/984
Another user has chimed in today that the same fix worked for him.

Update Ubuntu install process based on feedback from 2 users

---

docs/hoon/library/2e.md

Updated syntax and examples. Also added documentation for `++muk` and `++mum`.
@joshuareagan @keatondunsford @vvisigoth

Updated 2e

---

docs/using/messaging.md

This stood out to me as super inconsistent.

Minor typo correction in chat docs.

---

docs/arvo/network.md

Fix broken examples in network.md

Change `bowl` to `bowl:gall` (network.md)

---

docs/using/install.md

minor change so that install on FreeBSD works

works on FreeBSD 10.4 and 11.2

---

docs/hoon/library/3d.md

Wrote documentation for mostly undocumented arms.

Wrote 3d.md

---

docs/jetting.md

A new manual on how to write a jet.

notes on jetting

---

docs/hoon/library/2h.md

Some examples here showed a different result than they would when tested in the Dojo

Fixed 2h examples

---

docs/pki/storage.md

My guess is that "main different" was a typo.

Possible typo in storage.md

---

learn/arvo/hoon.udon
learn/arvo/style.udon

Edits the prose in the style guide and fixes some links

Style guide edits

---

learn/arvo/workbook.udon
learn/arvo/workbook/bomb.udon
learn/arvo/workbook/caesar.udon
learn/arvo/workbook/digits.udon
learn/arvo/workbook/eightball.udon
learn/arvo/workbook/recursion.udon
learn/arvo/workbook/traffic-light.udon

Adds workbook content to this repo. We're monorepoing this now.

adds workbook

---

learn/arvo/hoon/the-subject-and-its-legs.udon

Please do check my logic/math on this.

fix: | operator recursive definition

---

introduction/arvo-vs-azimuth.udon
learn/arvo/hoon/arms-and-cores.udon
learn/arvo/hoon/atoms-auras-and-simple-cell-types.udon
learn/arvo/hoon/cores-again.udon
learn/arvo/hoon/cores.udon
learn/arvo/hoon/examples.udon
learn/arvo/hoon/gates.udon
learn/arvo/hoon/getting-started.udon
learn/arvo/hoon/hoon-programs.udon
learn/arvo/hoon/hoon-syntax.udon
learn/arvo/hoon/lists.udon
learn/arvo/hoon/multi-gate-cores-and-doors.udon
learn/arvo/hoon/nouns.udon
learn/arvo/hoon/simple-one-gate-programs.udon
learn/arvo/hoon/structures-and-complex-types.udon
learn/arvo/hoon/the-subject-and-its-legs.udon
learn/arvo/hoon/trees-sets-and-maps.udon
learn/arvo/hoon/type-checking-and-type-inference.udon

Also did some minor reordering

adds 'next' link at bottom of lessons

---

introduction/contributing.udon

Gently massaged from the google doc

adds 'decorum' section

---

learn/arvo/nock.udon
learn/arvo/vere.udon

Addresses https://github.com/urbit/docs/issues/377 and https://github.com/urbit/docs/issues/376

adds child links to vere.udon and nock.udon

---

reference/hoon-expressions/rune.udon

Adds links to runes.udon

---

introduction/community-tutorials.udon

this addresses @galenwp's feedback on this section

Changes the list in community-tutorials.udon

---

introduction.udon
introduction/source-code-overview.udon
reference.udon
reference/hoon-expressions.udon
reference/hoon-expressions/limb.udon

This addresses a few of @galenwp's concerns

adds child-links to various pages, fixes formatting

---

introduction/arvo-vs-azimuth.udon
learn/azimuth.udon

This is more or less a complete rewrite. I took it out of the weeds and made it clearer. @galenwp, I am curious about your opinion on this new copy.

updates arvo-vs-azimuth.udon

---

getting-started.udon

This improves the document. Gets rid of some weird stuff where we assume prior knowledge of the wallet generator. Also boils down the "Bridge" section and makes the setting of the networking seed clearer.

updates getting-started.udon

---

learn/arvo/hoon/examples.udon

Now it points to type polymorphism.

added 'next' link to 2.11

---

reference/hoon-expressions/rune/zap.udon

Add missing indefinite articles in the !> docs.

Unsoviet grammar

---

reference/hoon-expressions/rune/col.udon
reference/hoon-expressions/rune/mic.udon
reference/hoon-expressions/rune/tis.udon
reference/hoon-expressions/rune/wut.udon

fulfills the request in https://github.com/urbit/docs/issues/422

changes 'Compiler macro' to 'Desugaring'

---

learn/arvo/hoon/hoon-syntax.udon
reference/glossary.udon
reference/hoon-expressions/rune.udon
reference/hoon-expressions/rune/buc.udon
reference/hoon-expressions/rune/lus.udon
reference/hoon-expressions/rune/mic.udon
reference/hoon-expressions/rune/sig.udon
reference/hoon-expressions/rune/tis.udon

Now that ~sorreg is gone, let us exorcise the last reglossing that everyone hates

Restore proper pronunciation guide

---

reference/hoon-expressions/rune/buc.udon

overzealous search and replace maybe?

faswork -> network

---

getting-started/installing-urbit.udon
learn/hoon/hoon-tutorial/hoon-syntax.udon

Addresses https://github.com/urbit/docs/issues/458

updates intructions so they work for MX Linux

---

concepts/azimuth/blockchain.udon
concepts/contributing.udon
concepts/technical-overview.udon
using/admin.udon
using/generators.udon
using/layout.udon
using/messaging.udon
using/sail.udon
using/shell.udon
using/udon.udon

fixes broken links

---

getting-started/operating-a-star.udon

Proposed touch-ups to star ops doc

---

concepts/azimuth/blockchain.udon

idk what kind of find-and-replace was run to mess this up (^:
Critical readers will complain that "but you can also do computation on Bitcoin!", but that's a topic for a different PR.

Fix weird word error

---

concepts/azimuth/wallet.udon

Add missing word

---

concepts/azimuth/wallet.udon

Addresses https://github.com/urbit/docs/issues/474

adds information about networking keys

---

getting-started/operating-a-star.md

Supersedes https://github.com/urbit/docs/pull/469

Update star operator instructions

---

getting-started/_index.md

Makes it easier to follow. This is the same content as https://github.com/urbit/docs/pull/466, but just with the new urbit.org.

updates getting-started index

---

getting-started/using-bridge.md

Update Bridge action description

---

getting-started/using-bridge.md

To try and combat confusion found in urbit/bridge#145.

Clarify context for accepting transfer

---

using/messaging.md

Hoping I did this to standards, or at least to standards for a trivial change.

Describing the argumentless form of ;what

---

learn/hoon/hoon-tutorial/recursion.md

The 'next up' link sent me back to the 'lists' page

Fix broken link in recursion.md

---

learn/hoon/hoon-tutorial/recursion.md

The intro calls recursion a common pattern, but doesn't explain what it is. This change fixes the issue described in #537.

Explain the concept of recursion during intro

---

learn/hoon/hoon-tutorial/conditionals.md

Conditionals change

---

reference/library/2n.md
reference/library/3a.md

please verify the `++exp:fo` doc fix

fix ++exp:fo docs, misc formatting fixes

---

learn/hoon/hoon-tutorial/nouns.md

Fix @ escapes in Nouns tutorial

---

learn/hoon/hoon-tutorial/trees-sets-and-maps.md

Also added a link and fixed a typo.

fixing dojo responses for week 2 of hoon 201

---

reference/hoon-expressions/rune/buc.md

One was broken (pat -> vat change), one was just pointing to the wrong rune

Fix some anchor links

---

learn/hoon/hoon-tutorial/ford.md

this fixes my pr from a minute ago

removed ford stub that should be in the ford branch

---

learn/hoon/hoon-tutorial/gates.md
learn/hoon/hoon-tutorial/list-of-numbers.md
learn/hoon/hoon-tutorial/setup.md
reference/arvo-glossary.md

I'm learning Hoon and doing I've found a few places in the documentation that can be easily improved to make the documentation more clear for newcomers like myself.

Fix typos, update arvo glossary and add missing steps

---

azimuth/creating-an-invite-pool.md

to reflect that you can assign invite pool to _any_ planet (not just your children)

udpate invite pool copy

---

tutorials/ship-troubleshooting.md

@philipcmonk, could you confirm that these instructions are correct?

updates to azimuth-tracker

---

tutorials/hoon/_index.md
tutorials/hoon/ford.md
tutorials/hoon/test-sets.md

This was done the dumb way since the original fork was done with the old file organization.

adding ford lesson

---

tutorials/hoon/doors.md
tutorials/hoon/generators.md

moves end of chapter 1 message

---

tutorials/hoon/doors.md

i made two branches with nearly identical names on accident lol

Door exercises

---

tutorials/hoon/_index.md
tutorials/hoon/atoms-auras-and-simple-cell-types.md
tutorials/hoon/bank-account.md
tutorials/hoon/conditionals.md
tutorials/hoon/ford.md
tutorials/hoon/generators.md
tutorials/hoon/hoon-syntax.md
tutorials/hoon/list-of-numbers.md
tutorials/hoon/nouns.md
tutorials/hoon/setup.md
tutorials/hoon/structures-and-complex-types.md
tutorials/hoon/test-sets.md
tutorials/hoon/the-subject-and-its-legs.md
tutorials/hoon/trees-sets-and-maps.md

also fixes some typos and style errors

Fix tutorial links

---

tutorials/hoon/doors.md

adds section on modifying door samples with $_

---

tutorials/hoon/egg-timer.md

Thanks @ohAitch for opening my eyes to the lies in front of me.

Correct move-card confusion

---

tutorials/hoon/hoon-syntax.md

This gives a little more mental scaffolding for the new Hooner. The only thing I am unsure of about this PR is whether I need to do anything else to make sure that the images are centered, since markdown down not support centering.

section on nesting runes, lego block diagrams

---

reference/hoon-expressions/rune/bar.md
reference/hoon-expressions/rune/buc.md
reference/hoon-expressions/rune/wut.md

Fixing pronunciations. See also https://github.com/urbit/urbit.org/pull/300

pad->pam, vat->pat, net->fas

---

tutorials/ship-troubleshooting.md

The next sentence shows how to recover communication with other ships.
(I told you a million times, don't exaggerate!)

Improve accuracy of claim

---

tutorials/hoon/gates.md

Simplify this sentence by removing "what ... is"
https://en.wikipedia.org/wiki/E-Prime

Simplify language with E-Prime

---

reference/library/2b.md

Docs for https://github.com/urbit/urbit/pull/1974

add into and snap

---

tutorials/guide-to-breaches.md

fix language

---

tutorials/guide-to-breaches.md

Adds warning about personal breaches

update guide to breaches

---

glossary/aqua.md
glossary/atom.md
glossary/behn.md
glossary/chat.md
glossary/clay.md
glossary/dill.md
glossary/ecliptic.md
glossary/eventlog.md
glossary/eyre.md
glossary/ford.md
glossary/galaxy.md
glossary/gall.md
glossary/mark.md
glossary/modulo.md
glossary/ota-updates.md
glossary/pill.md
glossary/senate.md
glossary/star.md

A few issues are important, eg. the glossary/galaxy.md
Overall good introduction to the Urbit system. I look forward to reviewing the tutorial pages.

Proofread docs for simple typos and clarity

---

glossary/eyre.md
glossary/iris.md
glossary/jael.md
glossary/vane.md

adds basic glossary entries

---

tutorials/hoon/the-subject-and-its-legs.md

fix exercise 1.6b

---

tutorials/arvo/arvo.md

Nothing to see here, citizen.
----
#

minor typos in arvo.md

---

tutorials/hoon/_index.md

fix link in hoon tutorial

---

glossary/hdwallet.md

proxies page is actually at ../proxies and not ../proxy

fixed broken link

---

glossary/dojo.md

addresses https://twitter.com/arthurcolle/status/1226202022178967554?s=21
----
#

tells how to change between chat and dojo

---

reference/hoon-expressions/rune/buc.md

Partially addresses #687
I am not sure that I use the word type/mold/structure correctly here so I need a
good eye on that.
I'm also not sure whether `$>` and `$<` can be used outside of getting types
from a `$%`. This is how it is used in all the code I looked at, but I didn't
comb the entire codebase for every instance of `$>`.
----
#

bucgal and bucgar runes

---

tutorials/arvo/gall.md

Fixes %pass to %agent cards in gall docs

---

reference/hoon-expressions/irregular.md

There was a line at the end saying to leave comments below. Our website doesn't
do this anymore, so it has been removed.
----
#

removes out of date info from irregular.md

---

tutorials/arvo/arvo.md

This addresses #835.
I used a "make PR from an issue" in Magit to make this PR and apparently this makes it look as old as the issue, but this is actually being posted 2020.04.16.

document %slip in arvo.md

---

reference/library/2b.md

Fix order of arguments b and c.
Fix return type.
Addresses issue #851

Make documentation of ++spin more accurate.

---

reference/hoon-expressions/rune/bar.md
reference/hoon-expressions/rune/buc.md
reference/hoon-expressions/rune/cen.md
reference/hoon-expressions/rune/col.md
reference/hoon-expressions/rune/constants.md
reference/hoon-expressions/rune/dot.md
reference/hoon-expressions/rune/ket.md
reference/hoon-expressions/rune/lus.md
reference/hoon-expressions/rune/mic.md
reference/hoon-expressions/rune/sig.md
reference/hoon-expressions/rune/terminators.md
reference/hoon-expressions/rune/tis.md
reference/hoon-expressions/rune/wut.md
reference/hoon-expressions/rune/zap.md

Partially addresses #874 but also this is just how it should have been all along.
----
#

adds backtics to headers for runes

---

tutorials/guide-to-breaches.md

I believe this changed with the OS1 redesign

Fix personal breach instructions

---

reference/hoon-expressions/rune/cen.md

censig regular form is 3-fixed

---

reference/library/table-of-contents.md

adds missing entry key:by to standard library toc

---

tutorials/hoon/caesar.md

Replace arm names w/ slightly more descriptive names.
Replace faces w/ slightly more descriptive faces.
Remove key argument from operate arm where it was not doing anything.
Add some extended description in various locations.
Added casting to the code for most arms.
Updated one exercise to add complexity (some students were just extending alpha arm w/ symbols)

Updating caesar.md for clarity

---

reference/library/4a.md

I do think its good to have a version number (per rune?) to indicate when the docs were updated ?
See also #676
I think I understand now that the way the dojo outputs stuff is changed, because I see this for more examples.
Is it even worth updating this ?
It can be confusing when you are learning ...

examples of output from ind:po and ins:po outdated

---

reference/vane-apis/ames.md

Nothing crazy here, just making style consistent.
----
#

fixes headers for Ames public API

---

reference/vane-apis/iris.md

fix iris header

---

reference/cheat-sheet.md

issue #902

---

tutorials/hoon/molds.md

issue #806

---

tutorials/arvo/cli-tutorial.md
tutorials/arvo/parsing.md

Just a couple things that should have made it into the original parsing doc PR.
I updated a reference from the CLI doc to link to the parsing doc, added the
grammar for the arithmetic expressions, and fixed a couple typos
----
#

parsing docs followup

---

glossary/delegated-sending.md

glossary typo

---

reference/library/4j.md

terminology: destroyer -> planet

---

glossary/breach.md
glossary/eventlog.md
glossary/pier.md
glossary/ship.md

Prompted by a question on-network; I've put this together to at least have a starting point for further definition.
Might have too much "operations" type information (breaching, backups etc) but it felt bare otherwise. Open to changes/comments if anyone has other ideas for what the entry should contain.

Create glossary entry for 'pier'

---

tutorials/hoon/parsing.md

fix typo in parsing tutorial

---

tutorials/hoon/hoon-school/libraries.md

Change the number of cards in a suite to 13 instead of 14.  (We were getting odd behavior in our blackjack program!)

Fix card span

---

tutorials/ship-troubleshooting.md

From comments in UC - there is nothing wrong with using Ctrl-Z and so the
corresponding section in `ship-troubleshooting.md` has been removed.
----
#

removes section on not using ctrl-z

---

glossary/clay.md

Fixes a broken link I spotted while reading the docs.

Fix broken link to vane.

---

glossary/arvo.md

delete 2 misleading lines from Arvo glossary

---

tutorials/arvo/arvo.md

arvo.md typo

---

tutorials/nock/explanation.md

The ordering of dojo output before was like A1 B1 A2 B2 which confused me
initially, since A/B were unrelated, so I changed it to A1 A2 then B1 B2.
----
#

clarifies nock 4 example

---

tutorials/guide-to-breaches.md

Addresses https://github.com/urbit/docs/pull/948/files/18868f9d3b106093c5076f0a2d159739ed647850
----
#

fix glossary links from breach page

---

tutorials/guide-to-breaches.md

See https://github.com/urbit/docs/pull/976
Also mentions how you can transfer without breaching
----
#

fix link again

---

reference/library/_index.md

adds gut:by to index

---

glossary/chat.md

I removed old terminology, and included information about how they work with groups and how DM's are handled.

updates chat glossary entry

---

tutorials/creating-an-invite-pool.md

invite pool addenda

---

reference/hoon-expressions/rune/buc.md

This PR splits off from #884 the introduction of the buc rune page, which got
roped into the `$|` rune entry PR and is responsible for the PR remaining open
for so long.
I've mostly rewritten the introduction/overview of buc runes, trying to
incorporate @joemfb's comments. This is mostly based off of my reading of the
compiler docs, which at the time I first wrote this PR I didn't know about. But
it seems to be the only place that really discusses what `spec` is.
I think I've managed to resolve most of my confusion on the relationship between
specs, types, molds, and validators. I wrote that `spec` are compile-time
values of `type`, which I'm not sure about, but I'm reasonable sure about
everything else.
I'm a little worried that my switching between e.g. `type` and type doesn't make …

rewrite buc rune intro

---

tutorials/hoon/hoon-school/libraries.md

Fix hoon school libraries typos

---

arvo/clay/clay.md

adds link to using/filesystem on clay overview

---

tutorials/azure-container-instances.md
tutorials/urbit-azure.jq

I have put this tutorial through a start-to-finish test-run, deploying a comet to Azure Container Instances and accessing its Landscape by putting its FQDN in my browser.
@jalehman

tutorial: Deploy a ship to Azure Container Instances

---

arvo/clay/architecture.md

Discussion from #1014 
cc @drbeefsupreme

Fix architecture.md to allow site to build

---

hoon/reference/stdlib/1a.md
hoon/reference/stdlib/1b.md
hoon/reference/stdlib/1c.md
hoon/reference/stdlib/2a.md

Reverts urbit/docs#1020
broken links

Revert "Add links to library docs 1a-2a"

---

hoon/hoon-school/gall.md

Extremely minor update to add a missing section header

Add missing section header

---

arvo/gall/overview.md
azimuth/azimuth.md
development/grants.md
glossary/azimuth.md
glossary/comet.md
glossary/keyfile.md
glossary/ship.md
hoon/hoon-school/setup.md

This is part of the effort to address https://github.com/urbit/urbit.org/issues/585 (see the companion PR for additional detail https://github.com/urbit/urbit.org/pull/588).
Fixes several path collisions in the documentation, as reported by latest version of `zola` (0.13.0)

Support latest version of Zola

---

arvo/clay/clay.md
arvo/clay/data-types.md
arvo/clay/using.md

Removes notices that some Clay docs weren't up to date

clay up to date

---

arvo/overview.md

The last sentence in the "Determinism" section was stuck halfway through a revision. I corrected the typo, taking a guess at what it was basically trying to say.

Correct small typo in Arvo overview

---

glossary/moon.md

Fleshed out the entry a little bit, added a link to the moon blog post.

moon glossary rewrite

---

userspace/gall/gall.md

lull not zuse

---

_index.md
development/project-repositories.md
system-overview/_index.md
userspace/landscape/_index.md

Some nonstandard uses of _comprise_.

Minor usage corrections
