docs/hoon/basic.md
docs/hoon/examples.md
docs/hoon/syntax.md
docs/hoon/twig.md

* In examples.md, added the relevant snippets of code immediately above the lines describing their function, to prevent readers from needing to scroll up and down continuously.
* Fixed a few typos and incomplete sentences.

typo fixes & example code more readily readable

---

docs/nock/implementations/groovy.md
docs/nock/implementations/hoon.md
docs/nock/implementations/scheme.md

After writing a Nock interpreter in Groovy #9 I've decided to rewrite it in Scheme. Groovy does not handle tail recursion really well and is bit slow. I've rewritten the Groovy code to use continuation-passing style tail recursion, but it didn't help too much - `StackOverflowError`s all over the place. (I've updated `groovy.md` to reflect the changes.)
The Scheme version benefits from the continuation-passing style recursion. A deep recursion basically runs forever (it does pollutes the stack/heap - don't know which one - but much slower). Anyway, I didn't know too much about CPS before, so it was worth digging into it a bit. The code is a direct rewrite of the Groovy one, no novelty here. Also, I haven't used Scheme since reading the The Little Schemer ages ago, so it might look ugly :) …

Nock interpreter in Scheme

---

docs/about/runtime.md

Typo fix - delete stray 'et tree.'

---

docs.md
docs/arvo/basic.md
docs/using/admin.md
docs/using/web.md

In order of visibility: 
1. Rewrite `docs/web.md` introcudtion to explain better the information within Nock/Hoon/Arvo.
1. `%s/aspie/academic/g`
1. Intro structure mirrors Urbit structure: style points
1. Some minor formatting in `/arvo/basic.md`
1. a blockquote explaining `*@`, which was used in the example.
1. Pronunciation guides for digraphs.
1. File == directory section for `/using/web`, along with the easter egg hint that editing `web.md` allows you to edit your default page at `some-ship.urbit.org`.

Friday afternoon doc-work

---

docs/hoon/twig/cen-call/sig-open.md
docs/hoon/twig/col-cell/hep-cons.md
docs/hoon/twig/ket-cast/hep-cast.md
docs/hoon/twig/ket-cast/lus-like.md
docs/hoon/twig/ket-cast/sig-burn.md

- moves irregular `:cast` form example from `:like` -> `:cast`, corrects formatting
- adds irregular form examples for `:cons` (quoting rules seem confusing without examples), corrects formatting
- fixes broken link from `:call` -> `:door`

minor Hoon twig corrections

---

docs/hoon/twig/bar-core.md
docs/hoon/twig/bar-core/cen-core.md
docs/hoon/twig/sig-hint/cen-fast.md
docs/hoon/twig/sig-hint/fas-funk.md

and corrects a link for `$core`...
Thus ends my whirlwind tour of the twig references

fixes duplicate file index (`:funk`), corrects typos

---

docs/using/web.md

The closing div tag was malformed.

Fix typo in web.md example

---

docs/hoon/twig/buc-mold/cen-book.md

Copy and paste error: 'buccen' was 'buctis'.

Fix buccen typo

---

docs/hoon/advanced.md
docs/hoon/exercises/data-structures.md
docs/hoon/library/2b.md
docs/hoon/library/2q.md
docs/hoon/reference.md
docs/hoon/twig/wut-test/gar-sure.md
docs/hoon/twig/wut-test/lus-deft.md
docs/hoon/twig/zap-wild/gar-wrap.md

A bit of a grab-bag here
- broken link in `:limb`
- incorrect runes in `?`
- commas in type assertions
- incorrect pretty-printing
Also, I added explicit links to `limbs` and `strings` for the hoon reference. The navigation gets a little confusing there, and I've often found myself backtracking through the nav to find those.

fixes some typos and links

---

docs/about/contributing.md
docs/arvo/basic.md
docs/arvo/generators.md
docs/arvo/http.md
docs/arvo/internals/eyre/commentary.md
docs/arvo/network.md
docs/arvo/state.md
docs/arvo/subject.md
docs/arvo/subscriptions.md
docs/arvo/web-apps.md
docs/hoon/exercises/fizzbuzz.md
docs/hoon/library/4h.md
docs/hoon/library/zuse/core/epur.md
docs/hoon/library/zuse/core/yu.md
docs/hoon/library/zuse/diff.md
docs/hoon/library/zuse/gate/jesc.md
docs/hoon/library/zuse/gate/tope.md
docs/hoon/syntax.md

Cleans up the formatting of the Arvo exercises, and fixes a couple of broken examples. Also fixes broken links in Arvo and elsewhere.
There are inconsistencies between relative and absolute links within the docs (there are both styles in this PR, as well). Do you have a preference between the two?

arvo exercises (formatting and broken examples)

---

docs/arvo/state.md

As proposed in the discussion for PR https://github.com/urbit/docs/pull/48, removes the solution to the Arvo/State chapter's first exercise ("Modify :examples-sum to reset the counter when you poke it with 0.") from the example code given. The code in the docs now matches that in the examples repo.

Remove solution to exercise in Arvo's State chapter

---

docs/using/messaging.md

also adds URL, command, and line-splitting examples
closes #52, #3
re #36, notes `ctrl-x` to switch from `:dojo`

adds line activation to :talk docs

---

docs/hoon/twig/bar-core/dot-trap.md
docs/hoon/twig/bar-core/hep-loop.md
docs/hoon/twig/bar-core/tar-gill.md
docs/hoon/twig/bar-core/tis-gate.md

to the relevant twigs (`|=`, `|*`, `|-`, and `|.`)
closes #24

adds explanation of :moar

---

docs/arvo/generators.md

Arvo's documentation on generators was showing hoon code for an unrelated application, rather than the appropriate mark. I replaced that with the `mar/examples/ping/message.hoon` mark's code [as available in the examples repository](https://github.com/urbit/examples/blob/master/gall/ping/mar/examples/ping/message.hoon), and simultaneously updated the code given for `app/examples/ping.hoon` (specifically, its header) to match that from the examples repository as well.
(Also fixed a small error in the generator code provided on that page, it had a `{` too many.)

Replaced incorrect example code in docs/arvo/generators

---

docs/hoon/library/2n.md

`++cury`'s source code was being shown under `++hard`'s documentation. Replaced it with `++hard`'s actual source code.

Provide actual ++hard source code.

---

docs/hoon/syntax.md
docs/using/web.md

**Overview**
In Hoon overview Syntax documentation, idiomatic rune FizzBuzz example:
- Actually use `end` face to determine program termination.
- Replace `text` with `pave` so output is identical to non-idiomatic rune example.
In Web usage documentation:
- Add note regarding file deletion bug in order to prevent confusion for new users attempting to follow documentation.
- Provide link to tree rendered version of `test.md` so users know where to go to see fully rendered result of JSX tag.

Fix: Several Documentation Issues

---

docs/hoon/library/2b.md

Also corrects a couple of examples
- `++spin` and `++spun` added in urbit/arvo#176
- `++find` and `++fand` added in urbit/arvo#186

adds stdlib docs for new gates (++find/++fand, ++spin/++spun)

---

docs/byte/1.md

* Add % to .y and .n (based on current dojo output)
* Fix the transposed type and representation of ~zod

Fix a few typos in the common irregulars section

---

docs/using/messaging.md

I've tried to learn my way around :talk twice now, and both times this unimplemented command has tripped me up. This seems like our good friend "premature documentation." Can we remove it to spare future urbit pioneers the confusion?

Remove unimplemented ;who <station> command

---

docs/arvo/generators.md
docs/arvo/subscriptions.md

sorry for the noisy diff. will pandoc separately in future.
* change 3 relative links to absolute ( which where broken: href="state" --> href="/docs/arvo/state" ) 
* pandoc

rogue links in arvo/generators.md

---

docs/hoon/twig/tis-flow/sig-tow.md

Don't know how to make this show up in the parent document lists. Set Sort: to 11 in the yaml. 
See #54.

Document =~

---

docs/hoon/library/2b.md

`++oust`, for deleting elements from lists, got added in urbit/arvo#241. This is the documentation for it.

Add documentation for ++oust

---

docs/about/runtime.md
docs/byte/0.md
docs/byte/1.md
docs/byte/2.md
docs/hoon/troubleshooting.md
docs/hoon/twig/sig-hint/lus-memo.md
docs/using/admin.md
docs/using/setup.md

As proposed in #36, all instances of key combo notations like `^X` have been replaced with `ctrl-x`.
Not entirely sure what to do about the output examples in Urbytes, ie:
> And we're done!  Press `ctrl-d` to exit:
```
~zod:dojo> ^D
$
```
I'd completely remove the `^D` there because it doesn't show up in the CLI either, but then what would those two lines be there for. Are they even necessary to begin with?

Consistently use ctrl-key instead of ^key

---

docs/byte/2.md

Typo fix: two colons.

---

docs.md

Looks like this:
Something that will definitely help make the learning process easier in
the meantime as we work on the larger doc reorganization. Added to the
current side panel. This arguably makes things a little long / crowded.
But I think the benefit > the cost as we try and figure out how to
create a better layout (like a Wiki layout of sorts, as we've
discussed).
The two community docs that come to mind are Joe's and Fang's. Are there
any more?
I think in the meantime I also need to revamp our short "readme" there to fill the white space. Can I give that a shot?

Add community docs to side panel.

---

docs/using/admin.md
docs/using/install.md
docs/using/setup.md

Most of our users are either likely simply getting their Urbit binary via 
`brew install`, or are following our docs/using/install step when building
from source to install the binary to usr/local/bin. Thus, the `bin/`
prefix to the Urbit admin commands in our current docs is kind of
unneeded and worse might cause confusion if the command doens't work 
the first time.
In this PR I added a note after our docs/using/install building-from-source 
blip to test that the `$ urbit` command works after installing to the user's path.

Remove `bin/` from docs/using commands.

---

docs/arvo.md

Screenshot:
I get that the idea originally here was for this section to be the "get
your hands dirty with Hoon fast" section. But for newcomers, I'd be
shocked if some people didn't confuse this with the place to start
overall. I.e., it doesn't make sense for this to be the Quickstart
section if `Install` is in a different section. Just `# Arvo` is fine.
It also makes the bottom grid row look prettier, as it's then the
progression: Arvo Hoon Nock. Plus, for learning Hoon, we likely want to
direct people to the Urbytes now, as many of us relay in Talk.
The url's are also docs/arvo so this just makes sense.

Arvo docs section `# Quickstart` to `# Arvo`.

---

docs/using/admin.md

When I first clicked on "basic operation" I was surprised to find Unixy admin stuff.  Broke it up into administration: everything "outside" of Urbit and operation: everything "inside" Urbit.  
At least it makes sense to me, I won't feel bad this gets kicked back.

changed basic operation to administration

---

docs/nock/example.md

Reversed a mistaken ordered pair from `[a b]` to `[b a]`; this was in the explanation of the subject passed to the loop arm.

Fixed a minor typo

---

docs/arvo/basic.md
docs/arvo/subject.md

I made a few small typographical fixes to the Arvo tutorial. I also added an extra hint to the **Basic Hoon** page that I thought should have been there when first working through the tutorial myself.

Small Tweaks to Docs

---

docs/using/filesystem.md

This patch got added to another pr I sent earlier.  Here it is by itself.

|sync examples had two on one line.

---

docs/hoon/concepts.md

Links now work for mint, twig, span, and limb.
Ran this through pandoc per the contributing docs, but not sure if that was the best idea since it makes the diff look much bigger than it really is.

Fixes #26: Adds proper anchor tags to sections for linking

---

docs/hoon/library/2i.md

Update examples to use modern hoon. (mo is no longer supported. Use (my which is currently considered the proper way to do this.
Corrects a couple other small syntax errors which were preventing some of the examples from running correctly. (e.g. incorrect back tics instead of single quotes and using a / instead of = on line 81)
The **urn:by** examples still don't work for me and I don't know enough to figure out why. Here's what I get when I run them:
```
> m
{[p='a' q=1] [p='b' q=2]}
> (~(urn by m) |=(a=[p=* q=*] q.a))
/~zod/home/~2017.6.14..18.23.05..c35f/arvo/ford:<[1.211 24].[1.211 52]>
-find.$
ford: build failed ~[/g/~zod/use/dojo/~zod/inn/hand /g/~zod/use/hood/~zod/out/dojo/drum/phat/~zod/dojo /d //term/1]
> (~(urn by m) |=(a=[p=* q=*] 7)) …
```

Fixes #180, Broken examples on the Hoon Map Library Page

---

docs/about/contributing.md

We don’t want people running pandoc against existing pages because it makes the diffs too hard to read. Also, newer pandocs respect the terminating --- in the yaml.

Clarify section in Contributing.md on pull requests against the docs.

---

docs/using/messaging.md

In a discussion in Talk last Friday, I learned for the first time that talk has the ability to turn timestamps on and off using the ;set command. As this was previously undocumented, I decided to add a section to the help doc that discusses talk.

Add information about turning timestamps on/off in talk

---

docs/arvo/network.md

A number of developers new to Urbit have been reading these docs and
running these examples, only to realize that booting a moon ships their
planets for unknown reasons. This is a simple doc fix that can push
people to comets in the meantime. And this is probably easier to do
than starting a moon anyways.
But maybe all of these docs should point people towards doing these on
fake ships? In an ideal Urbit world, dumb examples never sink your
planet, but unfortunately this can be the case now, and perhaps we
should make that explicit to early developer adopters.

Arvo network message doc: Boot a comet, not a moon

---

docs/arvo/internals/ford/commentary.md
docs/arvo/internals/ford/runes.md

Here's the rendered markdown of the new file:
https://github.com/urbit/docs/blob/ford-docs/docs/arvo/internals/ford/runes.md
This should show up as a link on the main ford docs page, under arvo internals.

docs for ford runes

---

docs/byte/1.md

We don't define casting before this point in Urbytes, so it would be helpful to emphasize the part of the example being referred to by "cast syntax".

Highlight what "cast syntax" is

---

docs/hoon/twig/sem-make/sem-fry.md

The old expansion of ;; was definitely wrong.  I adjusted it so it now matches the relevant code in ++open of hoon.hoon:
https://github.com/urbit/arvo/blob/eee8697782c04e6cbb33a1df682c5fcfa6ccb91d/sys/hoon.hoon#L6724

fixing an incorrect expansion of ;;

---

docs/byte/1.md

This example is broken (issue #145).
We still have people trying this out in :dojo and becoming confused when it doesn't work.  Someone was struggling with this today and brought it up in urbit-meta.  We should delete it for now.  Broken examples are frustrating.  When the problem in #145 is corrected, then we can (and should) add it back in.

Removed broken `? ~~Ürbit` example

---

docs/hoon/syntax.md

....or at least linking them to the glossary.  Some of the explanations I give are pretty dumb, but in these cases a link to the real definition is right there.  I think this kind of bootstrapping can be useful, but maybe it's too inexact.  Slap me down if you must, but let's not leave this doc as unfriendly as it currently is for beginners.

Partial Rewrite of Hoon Syntax doc

---

developer/docs/arvo/api.md
developer/docs/arvo/basic.md
developer/docs/arvo/generators.md
developer/docs/arvo/http.md
developer/docs/arvo/marks.md
developer/docs/arvo/network.md
developer/docs/arvo/security-driver.md
developer/docs/arvo/state.md
developer/docs/arvo/subject.md
developer/docs/arvo/subscriptions.md
developer/docs/arvo/web-apps.md

Updated code blocks and explanations to comply with Hoon %143 using urbit/examples:retrofit branch. Progress up through `security-driver.md`. I think `app/gh.hoon` needs to be fixed before I can continue work on the `api.md` doc as the GitHub issues exploration doesn't work correctly for me. I'll be looking into that further soon...

Arvo retrofit

---

docs/hoon/concepts.md
docs/hoon/demo.md
docs/hoon/reference.md
docs/hoon/syntax.md

Minor revisions, clarifications, removing the words "twig" and "span" from the Syntax and Concepts docs.

Update to Demo, Syntax, and Concepts docs

---

docs/hoon/rune/wut/zap.md

Fix the title for "wutzap" entry to show the rune `?!` instead of `?:`

Typo: wutzap

---

docs/hoon/library/4f.md

Fixed small layout problem in ++sear doc (4f.md).

---

docs/hoon/library/2b.md
docs/hoon/library/2i.md
docs/hoon/library/2n.md
docs/hoon/library/3g.md
docs/hoon/library/4f.md

`++hard` has a code/comment change to match the current `hoon.hoon` on `master`.
`++soft` has a comment change to match the current `hoon.hoon` on `master`.

Replace $-(* *) with gate.  This matches PR #618 in the arvo repository.

---

docs/using/setup.md

This caused some confusion, someone tried running the stated command as-is.
Though it's really not a huge issue, I see no reason not to use a shipname and ticket that is obviously fake.

Make example planet + ticket more obviously fake.

---

docs/arvo/basic.md

The current version indicates to readers that it p1.hoon should be run from the home desk rather than from the new examples desk. And apparently file inclusions are usually concatenated with hep instead of fas, so I changed that. Both +project-euler-p1 and +project-euler/p1 work, though.

Update basic.md to clarify how to run p1.hoon

---

docs/about/glossary.md

in a few locations it looks like there were URLs with an old scheme

fixed dead links

---

docs/arvo/network.md

Readers are given mixed signals by trying to start the app from the home desk without putting the `%examples` path in. By following these docs, readers will not have an `app/echo.hoon` under the home desk.
Also, out of nowhere comes `:examples-echo` right after an `:echo` command. I'm not sure why this is. I think my changes make things clearer. I also fixed /twig dead links

removed confusing path concatenation

---

docs/using/install.md

This is a first draft of changes to the install documentation for meson. It works for brew based systems, but macports and all the other package managers still need to be updated.

Change to meson

---

docs/hoon/rune/bar.md
docs/hoon/rune/buc.md
docs/hoon/rune/cen.md
docs/hoon/rune/col.md
docs/hoon/rune/dot.md
docs/hoon/rune/ket.md
docs/hoon/rune/sem.md
docs/hoon/rune/sig.md
docs/hoon/rune/tis.md
docs/hoon/rune/wut.md
docs/hoon/rune/zap.md

The rune category pages inaccurately (and inconsistently) designated expressions as either "Twigs" or "Stems"

updates terminology for rune reference pages

---

docs/using/install.md

Installation instructions worked on the Mac, but didn't work on AWS.  When I tried to run `urbit` I got this:
```
urbit: error while loading shared libraries: liblibuv.so.1: cannot open shared object file: No such file or directory
```
Digging around in the `build` directory, it looked like `ninja` could install all the libraries if you asked it to, i.e. do `meson-install`.  So that's what the updated instructions call out.
In my case, I had decided to use `linuxbrew` on AWS, which installs `ninja` somewhere outside of `root`'s path.  Hence the command for `linuxbrew` copies the user's PATH over to `root` before running `ninja`.

Update install instructions to use ninja to install urbit and libraries

---

docs/hoon/demo.md

The current version uses too many new concepts, uses a standard library function when `< >` will do, uses the phonetic rune naming before it's been introduced, and had some overlong explanations.  The goal is just to build newbie confidence that they can understand Hoon fizzbuzz, so we want to lighten the cognitive burden in any way we can.

simplifying demo.md

---

docs/hoon/rune/tis/lus.md

it won't work in the dojo with two spaces between foo and |=

replace gap with ace between foo and |=

---

readme.md

The markdown is interpreting `urbit.org/docs` as `https://github.com/urbit/docs/blob/master/urbit.org/docs`.
Adding `https://` think that should fix it.

Fix relative link bug in URL

---

docs/hoon/rune/tis/com.md

I mistakenly merged the previous PR for the new `=,` rune page.  Complaints about this new rune page can go here.  I also added an example at @belisarius222 's request.

adding example to illicitly added =, rune doc

---

docs/using/install.md

If users have meson v0.45.0 the build instructions will fail.
These docs add a workaround.

notes on problems with meson

---

docs/using/install.md

These instructions will build on Google Cloud Platform Red Hat Enterprise Linux 6.1 and 7.1
Final step (cping the urbit binary) does not work.  Will do more work on that, if desired.

install instructions now work for RHEL 6.1 and 7.1

---

docs/hoon/library/2b.md

Adding a note that `++turn` is Hoon's version of Haskell's 'map'

Adding a comment to `++turn`

---

getting-started.udon

Current release-candidate fails to build (in libent) with meson 0.29, but builds fine with latest (0.49).
Maybe we want to pin to 0.49 instead of going with "whatever is latest"? But we already weren't specifying a specific version in the macOS or Arch install instructions, so...

Remove explicit meson version from install instructions

---

getting-started.udon

The masses cannot freely join /urbit-meta or /urbit-help anymore, so getting-started.udon has been updated to tell them how to request access to stuff on landscape

added landscape instructions

---

reference/hoon-expressions/rune/wut.udon

It had the type pattern, but not the noun under test.

Fix wuthep pseudocode

---

reference/hoon-expressions/rune/wut.udon

the `?=`s only had one argument

Fixes wutlus pseudocode

---

learn/arvo/arvo-internals/ames.udon
learn/arvo/arvo-internals/clay.udon
learn/arvo/arvo-internals/ford.udon
learn/arvo/arvo-internals/gall.udon
reference/library/2q.udon
reference/library/5f.udon

I erred on the side of being overly specific within vane documentation: I replaced things like `++ankh` with `++ankh:clay`, and so forth

updates old-zuse names

---

getting-started.udon
learn/azimuth.udon

I couldn't build on Debian 9 with current script because the meson version was so old.

Remove meson version from bash install script

---

reference/glossary.udon

This fixes a typo in the Gall section that had referred to Ford, and also updates the "more info" link to match the newer scheme used throughout the docs.

Fix Gall text/hyperlink in glossary.

---

reference/hoon-expressions/rune/zap.udon

Said "turn on" while it should say "turn off"
https://github.com/urbit/docs/issues/383

Fix !. description

---

learn/arvo/hoon/trees-sets-and-maps.udon

Now the link points to 2.11 instead of 3.1

"next" link of trees-sets-maps corrected

---

learn/arvo/arvo-internals/admin.udon

I tested `-G` and `-k` flags, and both ways of creating `<keyfile>`.

Updated docs for booting a moon.

---

getting-started/azimuth.udon

The "login" options are clarified here, because they have implications for the messiest part of Bridge: setting networking keys.

clarifies Bridge instructions

---

getting-started/installing-urbit.udon

I just did this on a fresh Fedora 29 linode instance and these instructions worked for me.
They're less involved than the Fedora instructions already there.

Added 'Fedora 29 (fresh linode)' build section.

---

using/messaging.udon

There were some out-of-date instructions about commands for joining and leaving channels.

updates messaging.udon instructions

---

learn/arvo/eyre.md
reference/glossary.md
using/messaging.md
using/shell.md

I used an empty `<span>` placed on the line above the "target" to embed an `id` to be linked to.  This is to separate the markdown from the html required for `id`s.
I replaced `<a>` tags of the form `<a id="some-id"/>` (`<a>` tags are not self-closing) with `<span>`s.
There were two places with `id="ixor"` in `learn/arvo/eyre.md` so I renamed the first one `view-ixor` but I can't tell if that's the right thing to do.
I deleted `(class "first child")` when converting `using/shell.md`.  I don't know if that's what we want.

convert sail syntax to markdown/html in md files

---

getting-started/using-bridge.md

As seen on [bridge/releases](https://github.com/urbit/bridge/releases).
Feels kinda hazardous to have instructions in two places for this very reason. But, they're unlikely to change again for a while, so eh.

Update Bridge instructions to match latest release

---

learn/azimuth.md

`learn/azimuth.md` needs to be temporarily re-added because the docs sidebar code can't handle the case where `learn` has only folders as children (it then simply doesn't render them).

re-add learn/azimuth.md

---

learn/arvo/eyre.md
learn/arvo/hall.md
learn/nock/implementations.md
reference/glossary.md
using/messaging.md
using/sail-and-udon.md

Headers in lists are no longer supported by our styles. This PR changes a couple of tables of contents to standard lists.
Also includes deletion of a bunch of random <span> tags I came across and remove colons at the end of some headers in the Glossary.

Remove list headers, delete some spurious span tags

---

getting-started/booting-a-ship.md

Removes the `~` from the point name for the instructions on how to boot a ship. Referencing issue: #516

Update booting-a-ship page to use proper point name syntax

---

reference/hoon-expressions/rune/buc.md

Looks like it got copied without modification from bucket.

Fix incorrect bucvat description

---

using/admin.md

An Urbit instance doesn't default to port 8080 — it appears to try and get started on port 80 proper, first. On my first onboarding session with Urbit, this mixed me up, since if you're running this locally, without any other HTTP server on that port (something the docs essentially suggest is a normal environment) _nothing_ appears on port 8080. 
My second installation on AWS replicated this, also launching on port 80. Seems to fit more cases than not, unless you're running an HTTP server that the Urbit process coexists on.
There seems to be reference to the HTTP port behaviour [here](https://github.com/urbit/urbit/blob/a42f2cbe5ccc591c148464444264c8f6c92776e3/vere/http.c#L994) and [here](https://github.com/urbit/urbit/blob/a42f2cbe5ccc591c148464444264c8f6c92776e3/vere/http.c#L1420), …

Default port is 80

---

getting-started/installing-urbit.md

In the AWS installation instructions, the two `libsigsegv-2.11-7.fc30.x86_64` URLs no longer work — I've updated them with their current locations. The package version is newer, but urbit still compiles, so I am assuming no breaking errors.
It seems like Fedora will just change the URLs as the packages update, so you may want to establish a local (urbit.org) location for the packages to prevent future breaking links.

Update libsigsegv-2.11-7.fc30.x86_64 URL locations

---

reference/glossary.md

Various links give a 404 on visit, so I amended them to their current locations.

Fixing broken links in the glossary

---

getting-started/_index.md
learn/hoon/hoon-tutorial/setup.md
using/_index.md
using/creating-a-comet.md

Perhaps a more controversial PR? The first part of the tutorial series repeats information found elsewhere in the documentation — and it even links to those parts at the start. It would be much clearer to just continue from those posts as a starting point. 
In addition the usage of 'ship' and 'comet' is inconsistent (and refers to a planet as a 'comet,' potentially confusing a new user after instructing that a comet has a long address), so I've made it consistently a *ship*.
Finally the last part talks as if the 'noun' section is immediately following, but then goes into generators, which is jarring for the onboarding flow. I've clarified that what's coming *first* is a simple program, and afterward we will discuss what nouns are.
Edit: PR in sum
- Eliminates comet setup information from …

1.1: Removing redundant information, clarifying flow

---

learn/hoon/hoon-tutorial/egg-timer.md

May or may not want to also explicitly mention in the description above that "contents of bowl can change depending on calling context", but I couldn't find a way to say "calling" and "context" without needing further explanation.
At least saying "current" more often implies all that!

Be more explicit about bowl contents

---

learn/hoon/hoon-tutorial/nouns.md

It seems to me that the reference to `../atoms-auras-and-simple-cell-types.udon` should point at the `.md` file instead.

Fix reference to .udon file.

---

learn/hoon/hoon-tutorial/nouns.md

Now that comets aren't the de facto introductory ship in the Hoon onboarding, referencing them is inconsistent. In my PR doing the former, I missed a reference to a comet — this PR smashes it back into dust. I love comets, but they have their place.

Remove reference to comets in Hoon tutorial

---

using/shell.md

Marks are currently fairly undocumented (removed with the `layout` page if I recall), but seem like a not insignificant aspect of creating applications. ~~That said, I sense it's in a transition phase, but in this interim period, it should still have some representation somewhere.~~ It appears that `&cord` conversions are now gone, as are `&md` conversions, but we can still convert Udon and `&hymn` and stack those conversions, too.
This PR, then, explains that mark conversions are written destination-first; that they can be stacked together; that some marks only convert to other marks; and that some marks essentially wrap / prepare a mark for conversion to its final, destination mark, using Udon as the source mark.
Feel free to adjust and propose if anything I've written is, well, _off …

Some mark conversion documentation

---

reference/hoon-expressions/rune/cen.md

Also places a period politely.
`### "cencol"` => `### %: "cencol"`

Adding cencol rune to its header.

---

reference/hoon-expressions/irregular.md

Some of the links point to the page for the second char of the rune, which doesn't list the rune in question

Fix links to runes in Irregular Forms page

---

reference/hoon-expressions/rune/bar.md
reference/hoon-expressions/rune/buc.md
reference/hoon-expressions/rune/col.md
reference/hoon-expressions/rune/ket.md
reference/hoon-expressions/rune/mic.md
reference/hoon-expressions/rune/tis.md
reference/hoon-expressions/rune/wut.md
reference/hoon-expressions/rune/zap.md

I kept running into this, so I checked them all, and they were each missing the col suffix rune — eg. `tiscol`, `barcol`, `buccol`, `colcol` et al. I added them.
I was wondering if this meant col suffix runes had rendering issues in the past. In my commit earlier today adding `cencol`, it rendered fine, so I checked the commit history, and it looks the col suffix runes were just a casualty of [this commit](https://github.com/urbit/docs/commit/f1229c17b955540fd2cbc760a26506f7b549406d#diff-8b4bfeb59044a1736c1846009587b102) during the transition from Udon to Markdown. In any case, this PR adds them back.

Adding runes with col suffixes to /rune/ pages

---

using/filesystem.md

Changed dojo prompts to what is actually displayed
Changed some examples to match existing filesystem
Fixed some universal address examples
Added missing section headers
I took the dojo prompts from the current era, not 0.8.0/cc-release.
I don't know if the prompts will change in 0.8.0.
`~lodleb-ritrul` could be changed to `~some-urbit`,
and `gen/example/hoon` no longer exists,
but I didn't change those.

Added some dojo prompts for consistency

---

learn/hoon/hoon-tutorial/type-checking-and-type-inference.md

The link at the bottom of 2.2 points to a missing page. I'm assuming the next link should point to 2.3

Fix broken link to next lesson in 2.2

---

reference/glossary.md

This seems to have been carried over from older docs, but probably shouldn't have been.
(Why? It's stale, it's meme-y. And it's annoying.)

Remove dated reasoning for loobeans

---

learn/hoon/hoon-tutorial/hoon-syntax.md

These were getting rendered incorrectly, markdown parsers stumbled over the `(` in the urls.

Properly escape URLs with (

---

concepts/source-code-overview.md
getting-started/contributing.md
getting-started/installing-urbit.md
learn/arvo/gall.md
learn/arvo/hall.md
learn/hoon/hoon-tutorial/doors.md

Describes how to download static binaries for macOS and 64-bit Linux, and replaces the instructions for other operating systems with a catch-all using Nix and nixpkgs.

Update getting-started/installing-urbit for 0.8.0.

---

learn/hoon/hoon-tutorial/hoon-syntax.md

I noticed some of the lesson links were off on this page –– updated them to make more sense.

Fixes lesson chronology/misnamed links

---

learn/hoon/hoon-tutorial/lists.md

Fixes a small typo.
Changes " . . .which have has items preceding the `~`. "  to ". . .which have items preceding the `~`."

Remove extraneous 'has' from lists page

---

learn/hoon/hoon-tutorial/lists.md
learn/hoon/hoon-tutorial/type-checking-and-type-inference.md
reference/hoon-expressions/rune/zap.md
using/sail-and-udon.md

https://meta.stackexchange.com/questions/82718/how-do-i-escape-a-backtick-within-in-line-code-in-markdown

list, inline code tic rendering, and zapgar output fixes

---

getting-started/booting-a-ship.md
learn/arvo/clay.md
reference/glossary.md
using/creating-a-development-ship.md
using/filesystem.md

We use `|commit %mount-point` now, so I found every mention of the Clay / Unix auto-sync that refers to 0.7.4 behaviour, and amended it with mentions of the current behaviour.

Amending all mentions of Clay auto-sync to Unix

---

concepts/azimuth.md

Was reading the Azimuth article, saw some stuff to amend -- like linking to the Node repos (and changing the name of the second one), changing "Aegean" to "Landscape" (there's no other mentions of Aegean in the docs and Landscape best fits what it describes), and so I am putting in a PR here.

Azimuth typos + removing "Aegean" mention

---

learn/hoon/hoon-tutorial/setup.md

The docs say to run a generator `mygen.hoon` you need to type `+myhoon <argument>` in the Dojo, but if I'm not mistaken it should be `+mygen <argument>`

Fix typo in setup.md

---

using/sail-and-udon.md

These changes aren't necessary for udon, but we're markdown...
(Three or more dashes is alternate markdown syntax for heading level 2 for non-empty previous lines.)

simulate udon rendering with markdown

---

reference/library/_index.md

Fixes #601. This PR, in conjunction with [urbit.org#163](https://github.com/urbit/urbit.org/pull/163), provides tooltips and metadata for every arm of the standard library.
- Converts all links in _index.md from inline Markdown to HTML
- Adds tooltip class to those links
- Provides new, brief descriptions for every arm of the library as `title` attributes (yes, I went to each page, and consistently and succinctly described the functionality; if I couldn't, I just used the summary the documentation itself used)
- This PR's text is de facto metadata for the entire standard library functionality, organised by its term. If you use some regex, you can transform this into JSON trivially and make it into anything you like — up to and including IDE extensions. VSCode could mouse over `flop`, …

Add summaries and metadata to the entire standard library list

---

learn/hoon/hoon-tutorial/ackermann.md

According to the [`wut` docs](https://github.com/urbit/docs/blob/master/reference/hoon-expressions/rune/wut.md), "It's bad style to use `?~` to test for any zero atom. Use it only for a true null, `~`." The [Ackermann function example](https://github.com/urbit/docs/blob/master/learn/hoon/hoon-tutorial/ackermann.md) uses `?~` to test for a zero atom, so this PR corrects this to the proper use of `?:`instead.

fix 0 test in Ackermann function

---

reference/library/4b.md

The docs incorrectly state that `++cass` and `++cuss` returns `cords`. They return `tapes`. This PR also updates the relevant examples, removing some that actually `nest-fail`, and synchronizes them between the two methods.

update cass and cuss

---

getting-started/installing-urbit.md

Simply bumps to the [latest release](https://github.com/urbit/urbit/releases/tag/v0.8.2).

Bump urbit version in install instructions.

---

learn/arvo/_index.md
learn/arvo/ames.md
learn/arvo/eyre.md
learn/arvo/gall.md

Removes references to `kiss` and replacing them with `task` where appropriate - protects readers from trying to figure out what the hell a `kiss` is (which was replaced with `task` a while back).

kiss -> task

---

learn/hoon/hoon-tutorial/libraries.md

Mainly for hoon school 201 week 1. It's kinda annoying ranking poker hands with aces as 1, even though you of course have to check both ways when it comes to straights.

Represent ace as 14 instead of 1 in libraries.md

---

reference/library/2a.md

`/` was changed to `]` instead of `=`

fixed syntax update errors in library 2a section

---

reference/hoon-errors.md

Small change, but I see no reason not to show the exact real-world copy for a syntax error.

More accurate syntax error example

---

tutorials/hoon/egg-timer.md

Small formatting change to make lists more readable.

List formatting for egg-timer example

---

tutorials/hoon/ackermann.md
tutorials/hoon/arms-and-cores.md
tutorials/hoon/atoms-auras-and-simple-cell-types.md
tutorials/hoon/bank-account.md
tutorials/hoon/caesar.md
tutorials/hoon/conditionals.md
tutorials/hoon/doors.md
tutorials/hoon/egg-timer.md
tutorials/hoon/fibonacci.md
tutorials/hoon/ford.md
tutorials/hoon/gates.md
tutorials/hoon/hoon-syntax.md
tutorials/hoon/iron-polymorphism.md
tutorials/hoon/lead-polymorphism.md
tutorials/hoon/libraries.md
tutorials/hoon/list-of-numbers.md
tutorials/hoon/lists.md
tutorials/hoon/nouns.md
tutorials/hoon/recursion.md
tutorials/hoon/setup.md
tutorials/hoon/structures-and-complex-types.md
tutorials/hoon/the-subject-and-its-legs.md
tutorials/hoon/trees-sets-and-maps.md
tutorials/hoon/type-checking-and-type-inference.md

as per Matilde's email that these links can now be generated automatically, I have removed the Next Up links at the end of each Hoon tutorial page

removed next up links

---

tutorials/arvo/ford.md

This is so that Ford runes are searchable in the search bar. One downside of this PR is that these headers included a short summary of what they did. That summary now appears in the search bar, but maybe it should be added back in somehow.
I imitated the style for the other searchable runes for the headers, am not 100% that it will work though, since these headers use e.g. `/-` instead of simply /-, which is what is used in the headers for the Hoon runes.

Changes headers on the Ford runes so that it is possible to address them

---

tutorials/creating-an-invite-pool.md

storage.cloud.google.com doesn't work for external read access. Direct to media.urbit.org works.

Fix invite pool image links

---

reference/library/2b.md
tutorials/hoon/ford.md

The 'Referentially transparent' diff is hard to read because the highlighting of the actual diffs isn't being shown for some reason.
Here they are (old/new):
"What this ultimately is that builds are deterministic,"
"What this ultimately means is that builds are deterministic,"
"and so the same build ran on the same source files will produce"
"and so the same build of the same source files will produce"
"the output is a pure function of the input and."
"the output is a pure function of the input."

fixes in library section 2b and ford tutorial

---

tutorials/arvo/behn.md

Discovered that the reason that behn.md disappeared from the Hoon tutorial was because it was copied over the Arvo Behn page. This restores the old Arvo Behn page (which is admittedly just a stub) and links to the Hoon one. This is better than having the same page in two places, and making vane documentation more complete is on the to-do list for this quarter.

restores old arvo/behn stub and links to hoon/behn tutorial

---

tutorials/guide-to-breaches.md

On Bridge, the checkbox `Trigger New Continuity Era` has been renamed `Breach Continuity`
https://github.com/urbit/bridge/pull/339

bridge: match docs to 'Breach Continuity' checkbox

---

reference/arvo-glossary.md

'This glossary only covers terms the Arvo side of the project.'  ----> 'This glossary only covers terms of the Arvo side of the project'
'A desk is independently revision-controlled branch of urbit filesystem.' -----> 'A desk is an independently revision-controlled branch of urbit filesystem.'

small grammatical fixes

---

tutorials/hoon/egg-timer.md

This triggered me. Also we were using `card` in place of `move` a bunch? Pretty sure the code wouldn't compile.
I have a couple other style changes I'd make, but they're a bit more aggressive, so just listing them here instead:
- `(pair bone card)` -> `[bone card]` because you never ever care about accessing these and `+pair` isn't exactly modern hoon.
- `+>.$` -> `+*  this  .` etc.
- `:_  ~  move` ->  `[move]~`, double-`:_`s are pretty hard to follow imo, and `[item]~` lists are pretty common in these contexts. (Alternatively, `[move ~]`.)

Egg timer code nit & corrections

---

tutorials/hoon/landscape-tile.md

The line in question appears twice in the file; once in the program listing, and again in an excerpt.  One has already been fixed in an earlier PR; this fixes the other.

recieved -> received in tutorials/hoon/landscape-tile.md

---

tutorials/hoon/setup.md

It's talking about committing things to home desk, but doesn't actually tell you to have the desk mounted first.

Add mount instructions to setup page

---

tutorials/hoon/arms-and-cores.md
tutorials/hoon/doors.md

The section on nesting cores was a bit misleading and didn't elaborate much on why you would do it. I've rewritten it to be more explicit about how core nesting works in the standard library and how it affects visibility of arms.
I did have a couple of exercises that I wrote a few days ago that I removed. I couldn't figure out why the first one behaved as it did and neither did @baudtack, so it seemed too technical to be included. The second one was rolled into the rewritten section.

rewrites section on nested cores

---

reference/hoon-expressions/rune/buc.md

The buccen **Discussion** states:
> Make sure the first item in your $% terminates, or the default will be an infinite loop!
The example for the default (`$:foo`) was wrong so I'm wondering if the text should say "last" instead of "first".
What does it mean to "terminate"?  A non-recursive structure?  If someone can give me an example of a non-terminating item I'll try it in the first and last spots and update the text, if needed.

Examples fixes for buc runes

---

tutorials/hoon/conditionals.md

Addresses #727 . @belisarius222 's points are good and I agree that it is better to present idiomatic code. It's also good to present more than one `wut` rune, moved the old code (with minor changes) to the "Other Runes" section, showing how to use `?:` and `?!` but also saying that doing so in this manner would be poor practice.

Conditionals

---

glossary/azimuth.md

now it should actually direct to bridge instead of to https://urbit.org/docs/glossary/azimuth/bridge.urbit.org

fixed bridge link in azimuth glossary page

---

reference/library/2i.md

adds key:by and val:by to map reference documentation.
Have used `++` despite it being inconsistent with the rest of the documentation, because `+-` is no longer used.

add key:by and val:by to map reference

---

reference/gall.md

Added gall reference documentation.
Documents each of the gall arms with an example app. I struggled to write meaningful examples for the reference documentation without a wider context, so I have written a small omnibus app. It uses almost all the features of gall, so the reader can understand the examples with context they can understand. Somewhat plagiarised from agent.txt, but has been reworked to fit more of a reference style document. 
cc @rmariani

add gall reference docs

---

reference/library/2b.md

These were using some weird construction to make a wrapper gate, probably for long-gone compatibility reasons. This just passes in the 
Also does a typecast instead of `limo`. Plenty of other examples seem to do so, and this is more common in recently-written hoon.

Modernize reel, roll, sort examples

---

tutorials/arvo/gall.md

This address #738. This is pretty much a copy and paste of @philipcmonk's agent.txt, I just added some hoon tags to some code blocks and made it clear where other words were names of arms.
As I mention in #738, I think this is high enough quality to just publish it as the new arvo/gall page at the same time Gall is updated with the breach, just so we can have current documentation (and given that the last major revision on our arvo/gall page was in 2016). I'll revisit it in the next few weeks for more serious editing.

updates arvo/gall material with agent.txt

---

glossary/jael.md

I checked a few potential places and didn't see that we explain exactly what life number and breach number are anywhere in the glossary (or even the docs for that matter). This doesn't seem like the right place to hide those definitions, but should probably be mentioned in the docs somewhere and linked to from here. I'll make an issue for it.

Corrects the description of Jael

---

glossary/chat.md

This was all kinds of messed up. I don't even know why we have glossary entries for hall and talk. They say they're dead, so why bother describing them?

More correct chat glossary entry

---

tutorials/hoon/_index.md
tutorials/hoon/style.md

Paired with [urbit.org/#333](https://github.com/urbit/urbit.org/pull/333). Strips the manual index from the Hoon tutorial (and the additional info — if it should be preserved *below the lesson list*, it should go into the template directly, unfortunately).
Also adds "Appendix:" to the Hoon Style Guide to make it a more logical section of the list; it's cleanly separated from the chapters and lessons.

remove manual hoon tutorial index

---

tutorials/arvo/arvo.md

I made various changes. The most substantial include changing the location of at least one paragraph, and chopping out certain sentences or even grafs. I also cut a bunch of the whitepaper quotes or integrated them into undifferentiated prose. 
Other notes:
- Make sure that the Anchor links in table of contents work as intended
- It isn’t clearly defined where “conceptual” stuff ends and where the technical part begins. We need to commit to this distinctions structurally or not make it. It seems to begin with `## The stack`.  I indicated this in the overview, but it should be done more elegantly. 
- “The stack” and “The kernel” both get real estate on the table of contents, but “the stack” is one line, certainly not enough to justify being a section.

editing pass of arvo.md

---

tutorials/ship-troubleshooting.md

----
Previous link was broken, and we don't really have any guide about how to update
to a new binary anywhere are far as I can tell, so I changed the link to go to
the install page per Rob's recommendation. But that is written from the
perspective of a completely new install and so is not exactly what the reader
would be expecting.
I definitely think we need to
explain this somewhere, so perhaps it would be better to write a couple
paragraphs about that somewhere and make it part of this PR.
#

fixes link on updating to a new binary

---

tutorials/ship-troubleshooting.md

|nuke was removed and one-way connectivity is not an issue as it once was

removes |nuke and OWC references

---

glossary/atom.md

Addresses #794
Looking at the original glossary plans, we never planned a page for auras (and
it definitely seems too minor to get its own page anyways). So I removed the
link and added a short description.
----
#

clarification of what an aura is

---

reference/hoon-expressions/rune/zap.md

Addresses #749
I noticed while editing this page that some of the marks like `%zpgr` don't
match what is in `hoon.hoon`. This sort of thing keeps coming up and needs a
overall strategy, and is nested inside of some larger docs issues. I'll make an
issue about this. In this case, I just went with what is listed in `hoon.hoon`
instead of what it "ought" to be.
----
#

added !< entry

---

glossary/ames.md
glossary/breach.md
tutorials/guide-to-breaches.md

Addresses #770
Currently we do not say anywhere what life and rift number are. I have added a
description in tutorials/guide-to-breaches.md defining these concepts, and added
a new glossary page on breaches that has a bidirectional link with the glossary
page on Ames that defines these terms as well.
I am a little foggy as to where this terminology really comes from - Ames,
Jael, or Azimuth. I emphasized the connection with Ames in these edits, but
could easily be convinced that I should talk more about Jael or Azimuth.
Thus I set `category = "arvo"` but that could be changed.
----
#

information about life and rift number

---

glossary/ames.md
glossary/breach.md
tutorials/guide-to-breaches.md

Addresses #770 and fixes #807. Somewhere along the line I got the wrong
impression of what rift number was and thought it referred to network continuty
number. This is now (hopefully) accurate.
I also added in commands to check any ship's life and rift number to the guide
to breaches, in addition to the `+keys` generator that checks your own. It might
make better sense to add that information to
using/operations/using-your-ship.md instead or in addition to putting it here.
I'll make that a separate PR.
----
#

Fixed life and rift number definition

---

tutorials/_index.md
tutorials/creating-an-invite-pool.md
tutorials/guide-to-breaches.md
tutorials/hoon-errors.md
tutorials/sail-and-udon.md
tutorials/ship-troubleshooting.md

This commit fixes some text/typo, typographic, capitalisation, formatting, and indentation related issues in the `Sail and Udon` tutorial.

tutorials/*.md: text, typographic, and formatting corrections

---

tutorials/arvo/gall.md

Needs you to pass in the outer agent core.
People were copy-pasting this and running it, and it was giving not-straightforward error messages.

gall intro: correct default-agent usage

---

tutorials/vere/jetting.md

This corrects the paths, but what is the new version of `scripts/build`?  Is it `sh/build-interface`?

Correct script paths for revised folder structure.

---

tutorials/hoon/doors.md

I noticed a typo while reading, so I opened a quick PR to fix it. The GitHub file editor seems to have messed with trailing newlines, so I can undo that if you'd like.

Fix typo in doors.md

---

reference/vane-apis/ames.md

This PR adds a new file, `references/vane-apis/ames.md`. This is very much a
work in progress, but I'm at the point where I need people to read over it to
help me out.
Unlike for the Behn page, I do specify some of what the arms return rather than
just the possible `gift`s. Not sure if this is worthy or not, but I'd like to be
consistent.
As with the Behn PR #817, I do not include any examples, and for the same
reason. I think engineers could product much better examples much faster than I
would by talking to engineers and writing them myself.
************
I've had some amount of trouble trying to figure out what `gift`s a given `task`
may return. Here are some specific questions:
I'm not sure on the returns for `%hear` and `%hole`. There are four arms in `ames.hoon`
named `+on-hear`, and …

Ames public API

---

reference/hoon-expressions/rune/mic.md

Dojo says something different now when `;;` is used incorrectly. Very minor PR.
----
#

updates error message for micmic

---

reference/vane-apis/behn.md

This PR adds a new page, `reference/vane-apis/behn.md`, that lists each of the
`task`s that Behn performs, what they do, and what `gift`s they may return in
response.
Some possible issues:
i) I include the source code for each arm. Since we currently do not have a way
to pull source automatically into the docs, this creates an issue where it could be
out of date quickly. I think I will probably remove it, but would like feedback
on that choice first. Furthermore, sometimes what each arm does is split into
several places (and this is especially true for other vanes), so showing the
source for just the arm can be deceptive.
ii) I am not yet an expert on reading Hoon, so I cannot be sure that I've
covered all possible `gift` responses correctly. I'm pretty sure I have for
Behn, but not as …

Behn public API

---

reference/vane-apis/gall.md

Changes `(unit path)` to  `(list path)` in the gall docs to match the updated gall cards

gall-reference: change unit to list in %fact card

---

reference/vane-apis/dill.md

This is a rough draft of documentation of the Dill public API. It is a work in progress and there are several areas that need work:
I don't understand how `%flow` works. It's a lark expression `+>` that is just the core it
is defined in and thus contains the card and I'm not sure what that gets sent
to. It has the form `[p=@tas q=(list gill:gall)]`
Similarly, `%harm` only appears as `+>` in `+call` in `dill.hoon` and the
associated card is empty. I don't see how this can do anything.
`$hook`, `$talk` appears in task:able:dill in `zuse.hoon` and has the comment "this term
hung up" but hook appears nowhere in `dill.hoon`. is `hook` deprecated?
I'm pretty sure what `%talk` does is print a `tape` to the screen, but following
along what is going on in `+from` is difficult.
The comments say …

Dill public api

---

tutorials/arvo/gall.md

I would call `old-state` `saved-state` and use "old" only for state _type_ stuff, like `old-state-types`.  But since all the existing apps use "old" instead of "saved" this is probably not worth pursuing.

Corrects ++on-load example code in gall tutorial

---

reference/hoon-expressions/rune/buc.md
reference/hoon-expressions/rune/ket.md

This is a small PR that removes two references to "factories", which seems to be
an old name for molds. I asked in the infrastructure channel if this terminology
was still used and a couple people commented that it is not.
----
#

remove references to factories

---

reference/hoon-expressions/rune/tis.md

Given the "evaluate when used" nature of =*, it's more accurately described as a
macro than an alias.
This is an attempted first pass at the copy here. Obviously rough around the edges, but kinda highlights already how =* is more clearly described as a macro. "It's calculated every time you use the macro" seems very obvious.
(Just a proposal, taking all challengers.)

rune: describe =* tistar as macro, not alias

---

tutorials/hoon/egg-timer.md

Complete rewrite of egg-timer.hoon example code and walkthrough, to work with static Gall.
Thanks to ~hastuc for walking me through this and ~palfun for helping with style/standards and my own understanding.
Regarding the tutorial itself, I tried to be consistent with other documentation, however I had to make best guesses in some cases. e.g., should we say `++on-poke` or `++  on poke`? Should we capitalize Core, Door, Arm?
Will require review both for style and content.

Updated egg-timer.md to static Gall

---

tutorials/arvo/gall.md

Redo of https://github.com/urbit/docs/pull/846.

gall: remove stray ser and unify ++on-poke examples in gall tutorial

---

tutorials/hoon/workbook/traffic-light.md

The wing expression `+>` translates to "return the tail of the tail", not "head of the tail".

Change "head" to "tail" in the traffic light workbook

---

tutorials/hoon/libraries.md

- In the `make-deck` walkthrough, I changed `j` to loop from 2 to 14 to correctly reflect the original code.
- In the `shuffle-deck` walkthrough, I changed the description of `=^` to be more clear. Originally, it said "changes the leg with a tail", which doesn't make much sense. I changed this to say "changes a leg in the subject with the tail".
- The `shuffle-deck` walkthrough also said that the code used the `%^` rune for recursion. I changed this to `%=` to match the code.

Fix typos in the libraries tutorial

---

reference/vane-apis/iris.md

This PR introduces `/docs/reference/vane-apis/iris.md`, which contains information on the `task`s that Iris can be passed.
I only have one lingering issue:
I'm a bit confused about how `%cancel-request`s are done. The corresponding
`task` has no arguments, so I assume that which fetch to be canceled must
correspond to the duct that the task came on and have written the entry for it based on that assumption, but I haven't understood the code well enough to know for sure that that is what is
happening. The rest of Iris seems to work on an ID number system, one for each http connection, and there are several comments that suggest that ducts should be used to keep track of connections

Iris public api

---

tutorials/hoon/bank-account.md

- fixed some grammar
- clarified the sentence about wing resolution and the fact that the arms create gates, which have the door as their subject at the time of creation.

Clarify wing resolution part of bank-account.md explanation

---

reference/library/3a.md

The description of signed integers (the @s type) was previously incorrect.

Fixed description of signed integers

---

reference/library/2b.md

The output of `(weld "urb" "it")` is incorrect.

Fix weld example output

---

tutorials/hoon/arms-and-cores.md

When I first wrote this part last year I didn't have a complete understanding of
what `=>` was doing, especially that `=> a b` where `a` and `b` are cores puts
`a` in the context of `b`. I've rephrased and expanded the section in `tutorials/hoon/arms-and-cores.md` about the
usage of this rune, added another example, and rephrased the associated
exercise.
One thing to note when reviewing this is that up until this point in Hoon
school, the payload of gates has been said to be `[sample context]` but the
general notion of cores (introduced in this section)
have only been said to have a `payload` and it had not yet been stated that a
payload is always a cell called `[sample context]`. In fact because of this, I am not actually
sure this is always how `+3:core` is named. Thus I think this …

Hoon school lesson on =>

---

reference/library/3g.md

It previosly had the source for `++hair` and the defintion looked wrong. I fixed
the source and rewrote what it does, though I am still not 100% certain why an
`+edge` has two `+hair`s.
Also fixed a link.
----
#

fixes +edge in std library reference

---

tutorials/hoon/molds.md
tutorials/hoon/type-polymorphism.md

This PR addresses #850. We previously implemented parametric polymorphism with
`+*`, but this is now done with `|$` and so I have changed the appropriate
section to fix this.
There are edits to two files: `molds.md` and `type-polymorphism.md`. We already
talk about `|$` in `molds.md` but this is before we introduce the notion of type
polymorphism. I think the lesson in `molds.md` is perfectly understandable
without explicitly saying what polymorphism is, but I think there could be an
argument made that we should just move the content there into
`type-polymorphism.md`. My argument against this is that the section on polymorphism (2.5) is
the most difficult section in all of Hoon school (at least it was for me), and
so introducing a chunk of that content in the prior section primes the …

parametric polymorphism done with |$

---

reference/library/4b.md
reference/library/4j.md
reference/library/4l.md
reference/library/4m.md
reference/library/4o.md
reference/library/5f.md
reference/library/_index.md
reference/library/table-of-contents.md
tutorials/arvo/eyre.md

This old terminology was all over the place in the standard library docs, and in
one spot on the Eyre doc. I just did a find-and-replace and didn't check
anything closely, hopefully we weren't using odor as some colorful language somewhere.
----
#

global replace of odor with aura

---

reference/vane-apis/airlock.md
reference/vane-apis/ames.md
reference/vane-apis/behn.md
reference/vane-apis/dill.md
reference/vane-apis/gall.md
reference/vane-apis/iris.md
tutorials/arvo/cli-tutorial.md
tutorials/arvo/move-trace.md

Since the title in the preamble of a document renders a header at the top of the
document, all of these listed the title twice once rendered on the site.
----
#

remove superfluous headers

---

reference/library/2n.md
tutorials/hoon/doors.md

Up until this point, I was under the impression that currying in Hoon was only
possible using doors and `%~`, which always seemed rather restrictive. I just
found `+cury` and `+curr`, and so have added a brief reference to them in the
lesson on doors, which is the only place in the Hoon tutorial that mentions
currying at the moment.
----
#

adds reference to +curr and +cury in Hoon school

---

reference/library/4f.md
tutorials/arvo/parsing.md

This PR is an elaboration on @Fang- 's parser notes (https://github.com/urbit/fora-posts/blob/0535da6992f9a81c89858b6598eda4bb41da7b26/archive/posts/~2016.12.21..21.54.21..cfd1~.md)
The overall goal of this document is both to familarize developers with how parsing works in
a functional programming language and how to write parsers for Hoon in
particular.
I've attempted to write for the reader who knows Hoon but has never written a
parser before (which was my own starting point).
There are three main parts:
1.  A short section describing what a parser does and how they are implemented in
functional programming languages.
2. A much longer section describing the particulars of writing parsers with
Hoon.
3. A walkthrough implementing a parser that parses arithmetic expressions and
returns …

Parsing tutorial

---

glossary/hall.md

Generally we've removed pages that refer to things that don't exist anymore. I
remember writing this entry when I had just started at Tlon and since it was on
the list of articles to write I didn't question why I was writing it.
----
#

removes hall.md

---

reference/hoon-expressions/rune/wut.md

wutlus was incorrectly listed as allowing a default with a constrained sample e.g.:
|=  vas=?(%a %b)  ?+(vas 240 %a 20 %b 42)
Corrected to have a @tas for type of vas.

Fix mint-vain error in wutlus

---

tutorials/arvo/ames.md

Just a short section on how Ames packets are structured as serial data. I will
be adding more to the Ames section over the next few weeks and this is
just a start.
I'll be focusing on information useful to the security auditors, which will
probably end up being close to having a story of the "journey of a packet" here,
which I think is what the Ames page used to have before that was made out of date.
----
#

Ames packet structure

---

tutorials/ship-troubleshooting.md

Currently there was only one place in all the docs that linked to the support
wiki, which was the docs index page. I've added a link to it to the top of
`ship-troubleshooting.md` as well as a couple of links to individual pages in a
couple sections of that page. I've also corrected or clarified a couple entries.
----
#

adds links to support wiki

---

tutorials/arvo/gall.md

Per @philipcmonk 's request #962 , I've added threads.txt to
the Gall page under `arvo/gall.md`. My only edits were adding in a couple links
and tagging code blocks with `hoon`.
----
#

add threads.txt to arvo/gall.md

---

tutorials/hoon/hoon-school/aqua.md

Current version gives a `%nest-fail`. The sample should be just a `vase`.

Sample change for thread:spider

---

tutorials/arvo/clay.md

This adds a section on merge strategies to the top. This was requested by
@vvisigoth. The remainder of the document is still the old Clay doc, some of
which is out of date. I plan to revise the remainder of this soon, but getting
the merge strategies in is important enough to edit it in now even though it
makes the organization all whack.
----
#

Clay merge strategies

---

tutorials/guide-to-breaches.md

Our docs on what happens when you change your ownership address were incomplete.
The main thing that was unclear is whether you need to check the `Breach
continuity` box (you do not). So I've revised the instructions to include this
information, as well as to point parts of the instructinos to the Using Bridge
page, so that when Bridge changes there is one fewer page to keep up to date.
----
#

breach instructions when changing Ethereum ownership address

---

reference/vane-apis/ames.md

This PR amends the Ames API doc to explain how `%plea` tasks ultimately end up
triggering Unix to send packets, which is via `%send` gifts in response to the
`%born` task.
----
#

%plea triggers %send which are in response to %born

---

glossary/comet.md
reference/library/2e.md
reference/library/2p.md
tutorials/arvo/ames.md

This is the second of several Ames PR's I've been working on (the first being #943), which are mostly being done now for the sake of the security audit but of course the information is widely useful. It is mostly an elaboration on what was already summarized at the top.
This adds two major sections:
- Packets: what format they come in, how they are encrypted, how they are serialized, how messages are packetized, how they are acked, and how they are relayed.
- The Serf and the King: The Serf does most of the grunt work for Ames, but the King has important responsibilities too.
Each section is accompanied by a diagram that helps to describe their content.
There are still some important things to come. A discussion of nacks and failures in Ames in general, how Ames and Jael work together to …

Ames - packets, diagrams, serf and king

---

tutorials/ship-troubleshooting.md

Includes instructions for resetting the code used to log in to Landscape.
Also replaces stale reference to urbit-help channel
----
#

|code %reset

---

tutorials/concepts/arch.md
tutorials/hoon/graph.md

Initial documentation for graph store
Initial documentation for basic landscape architecture to orient userspace developers
Intent is to provide outside developers a clear path for interacting with the standard suite of urbit userspace apps that are backed by graph store

landscape arch and graphstore docs

---

tutorials/arvo/arvo.md

The first part of this document is not out of date and the warning is scary.
This moves the warning to the kernel section.
Per @jalehman 's suggestion
----
#

moving arvo out of date warning

---

tutorials/concepts/azimuth.md

Addresses #998 as well as partially addresses #955 and #930. Will need to be
edited to link `claz` when #991 is merged.
One outstanding question: I am not certain that the `@q` `T` is actually the
master ticket. Is it actually `E`? When you receive an email invite, you get a
~four-word-camel-case phrase to put into Bridge which then generates a different
~four-word-camel-case phrase that is actually your master ticket. Based on my
reading of
https://github.com/urbit/proposals/blob/master/008-urbit-hd-wallet.md, it is
unclear to me whether the invitation ~four-word-camel-case phrase is actually
`T` and the master ticket is `E`, or if the invitation phrase isn't included in
this document at all. @Fang- ?
----
#

HD wallet generation, hardware wallets, hot and cold wallets

---

tutorials/vere/jetting.md

Cell composition, not list composition, is referred to by `u3nc` _y amigos_.
`u3nc` simply composes two bare atoms:  it does not actually form a list from them.
To form a list, you have to append `u3_nul` as appropriate.

Correct language re jetting.

---

tutorials/hoon/parsing.md

example used `lit` and `rit` where `pal` and `par` are proper now.
example previously had a syntax error on line 2:
`|^  (scan xprs tape)` corrected to `|^  (scan xprs expr)`

Fixed example in parsing.md

---

reference/hoon-expressions/rune/dot.md

The dotket doc entry has a minor typo where `p` should be `q`

Fix typo in dotket documentation.

---

reference/vane-apis/jael.md

This PR adds `/docs/reference/vane-apis/jael.md`. It describes `task`s that can
be `%pass`ed to Jael and what `gift`s may be returned in response.
Edit 2020.12.03 - finally looped back to this! My only outstanding question is that the comment above the `%moon` task says its for changing private keys, but the code looks like it changes public keys. I ignored the comment, but I also don't know the details on how moon keys are stored, so perhaps it really does store private keys but uses the `+public-keys:feel` arm.
I also finally came to the conclusion that including `%pass`es that a `task` can trigger might be considered an implementation detail and thus doesn't necessarily belong in an API doc. I'm not really sure on this. I have chosen the worst path, the middle one, and so have a few …

Jael public API

---

reference/vane-apis/jael.md

Changing the title to be in alignment with the other API docs
Also I think I have initially put an unnecessary markdown header at the top of every one of the API docs I've wrote. Maybe I'll finally learn my lesson next time.

fix jael APi title and header

---

tutorials/hoon/hoon-school/bank-account.md

There is an extra "we that" in one of the lines.
Remove to change line from
"...core we that that we examine below"
to
"...core that we examine below".

Fix hoon school bank account typo

---

tutorials/hoon/hoon-school/type-checking-and-type-inference.md

There is an extra "of" that either should be removed or needs other words added to it to be meaningful. In 80b739a, I remove it.

Fix hoon school type checking typo

---

tutorials/hoon/hoon-school/structures-and-complex-types.md

In the discussion of type casting, the irregular type cast renders incorrectly.
This is one way to fix the rendering (at least for the grip markdown rendering tool).
See attached images:

Fix hoon school structures & complex types typo

---

tutorials/hoon/hoon-school/molds.md

`each` is referred to with an extra `++` prefix.

Fix hoon school molds typo

---

reference/hoon-expressions/advanced.md

Was reading this page and noticed the code was out of date.
Went through the text as well to make sure I didn't mess up any references.
There was one part though that looked like it was already wrong even before -
starting at L200:
```
If a name is in the q.p map, it's a bridge. 
```
`tune` only had one `map`, and the line commented with `::bridges` is a `(list
hoon)`. Since a `%face` is a `p=$@(term tune) q=type`, I guessed that it meant
the `term` here, but I think I am still a little mistaken. So I need some
guidance here.
Tagging @jtobin since I ran into this while reading compiler documentation,
which we're supposed to work on together after the new year, which will
hopefully be accompanied by some improvements to the docs on the type system.
----
#

updating code on advanced types

---

hoon/hoon-school/atoms-auras-and-simple-cell-types.md
hoon/reference/_index.md
hoon/reference/auras.md

Added a page with a list of commonly used auras. Up til now, the only reference we had was buried in the Hoon school notes. This was lifted more or less directly from https://github.com/natareo/hooncard/blob/master/hooncard.pdf h/t to @sigilante

auras reference

---

arvo/clay/architecture.md
arvo/clay/clay.md

This PR brings `arvo/clay/architecture.md` up to date. This was mostly minor
changes to formatting, but also removed inaccurate information on `+sted` and
added what replaced it, as well as what `+form` is for.
I also marked the Clay overview page to say that this page is up to date.

clay architecture cleanup

---

userspace/threads/basics/fundamentals.md

accidently left the image on my s3. Has now been uploaded to to urbit.org s3

Change threads diagram image url to media.urbit.org

---

hoon/reference/rune/mic.md

Adds an entry for `;<` to the rune docs. Addresses #1032
h/t to @juped and @sigilante whose discussion in the Hoon school chat I lifted
much of this from.
Possible outstanding issues:
- Not sure that my example combining `+biff` and `+bind` is clear, given how
`+bind` seems to treat gates that produce units as though they do not,
leading to swapping their order in the sequence being commutative.
- Many runes have an "expands to" section, but some of them do not. Does this
rune expand? How can I tell? I got the desugaring from looking at the parser
in `hoon.hoon`, but I don't know where to look for "expands to".

micgal entry

---

userspace/_index.md
userspace/graph-store/advanced-info.md
userspace/graph-store/data-structure-overview.md
userspace/graph-store/validator-walkthrough.md

- Added `hoon` to code blocks for syntax highlighting
- Added reference to Graph Store docs in userspace `_index.md` (fixes https://github.com/urbit/urbit/issues/4761)

Minor tweaks to graph store documentation

---

development/project-repositories.md

Fix typo in Project Repositories documentation

---

azimuth/_index.md
azimuth/advanced-azimuth-tools.md
azimuth/life-and-rift.md
glossary/breach.md

Addresses #980
Our description of life and rift has been incomplete and perhaps mildly misleading for some time. I've made a new page addressing this which I've put in the Azimuth section, though since these concepts also apply to moons and comets, I had also considered putting this page in the Ames section. It might make sense to rename the Azimuth section to Urbit ID to be more encompassing, but that can be a separate PR.
This is accompanied by changes to the using docs, which I'll put up a PR for in the urbit.org repo shortly.

add page on life and rift

---

hoon/reference/stdlib/2i.md
hoon/reference/stdlib/_index.md

remove def:by from reference

---

glossary/docvote.md
glossary/ecliptic.md
glossary/senate.md
glossary/upgrade.md
glossary/voting.md

We're about to release a blog post about the current Ecliptic upgrade proposal in the Senate, but we don't actually have a glossary page about it.
This adds one. I realized writing it that I am not 100% certain on the mechanics, so please take a gander @Fang- 
See #808

add upgrade proposals to glossary

---

hoon/hoon-school/doors.md
hoon/hoon-school/lists.md

This small modification adds a little more to the lesson on doors (`doors.md`),
showing that they really are identical to cores with samples at the level of
Nock.
I make use of the `=>` rune, which I noticed was first used in `lists.md` but
never explained there. So I added a short explanation there of what `=>` is, as
well as a link to the later lesson that goes into more detail
(`arms-and-cores.md`, which comes before `doors.md`).
The exact placement of information in Hoon school can make a big difference, so
if anyone thinks there's a better spot for this please say so. I'm pretty
satisfied with where its at, since we introduce the rune for doors and then
immediately call back to something the student will already be familiar with and
shows that they're the same.

hoon school - doors are cores with samples

---

azimuth/azimuth.md

The language we use to refer to Ecliptic is inconsistent. On this page, we
repeateadly call it "the Ecliptic", while everywhere else we seem to just call
it "Ecliptic". While this "the Eclikptic" is closer to its usage as an
astronomical term, we use it as a proper noun to refer to a particular Ethereum
contract, so if we're saying "the" then I think it ought to be The Ecliptic. My
personal opinion is that calling it "The Ecliptic" just sounds weird and we
should just call it Ecliptic, as we do in other places in the documentation and
on the blog.
This is 100% a matter of personal opinion. I'm just noting an inconsistency in
our usage and choosing my preference of how to resolve that inconsistency, but
if anyone feels strongly otherwise then please say so.

the ecliptic -> ecliptic

---

arvo/reference/filesystem.md

Addresses #855
I give a brief description of what each folder is used for, and go into more
detail for `/sys`.
This page might be trying to be too many different things at once. It might
better belong in the `arvo/concepts` folder instead of `arvo/reference`. For
instance, I mention what dojo syntax to use to run generators and threads, as
well as Ford runes. I also describe how the subject is built up from the files
in `/sys`, which while interesting, might be more appropriately tacked onto
`/arvo/overview.md` rather than here.
@Fang- said the dependencies for the files in `/sys` is `hoon->lull->arvo->zuse`
but peeking around inside it looked like it was `hoon->arvo->lull->zuse`
https://github.com/urbit/docs/pull/1091#issuecomment-857961935 not sure if he
made a typo or I'm …

adds page describing filesystem hierarchy

---

hoon/reference/irregular.md

This addresses #1016 and #1064
I replaced the terse "I:" and "R:" with "Regular:" and "Irregular:", and put the
entries onto separate lines.
I also added a couple missing entries, for `^*` and `^:`. I didn't even realize
that bunting with `*` was an irregular form since `^*` has never been on this
page. These could be separate PR's but they're all so minor I decided to do them together.
Also, I am under the impression that `^:` is no longer relevant since all molds
crash when you feed them a value of the wrong type. Nonetheless, it still
appears in the codebase, so we ought to have it documented while it lingers. I
can't seem to find the conversation I remember having about this though, so
please correct me if I am mistaken. If so, I should go edit the `ket.md` page to
say as much.

irregular.md: add ^* and ^:, adds spacing, more verbose
